### Site Settings ###
title               : Aji Setiawan
description         : >-
                      Mahasiswa Program Studi Manajemen Bisnis Syariah, Desainer Grafis, Webgrammer amatiran. 
                      Lihat proyek, portofolio, tulisan dan profilku di menu pojok kanan atas.
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : ajisetiawan716/ajisetiawan716.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : thedevslot/WhatATheme
open_new_tab        : false                             # Opens external URLs in new tab (works for posts, projects and navbar only)


### Plugins ###
plugins: 
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md/**                           # For Documentation Only


### Author Info ###
author:
  name              : Aji Setiawan 
  image             : https://avatars.githubusercontent.com/u/106381048?v=4
# behance           : your_username
# dribbble          : your_username
  email             : ajisetiawan716@gmail.com
  facebook          : adjiee.setiawan
  github            : ajisetiawan716
# gitlab            : your_username
  instagram         : ajisetiawan716
# kaggle            : your_username
  linkedin          : ajisetiawan716
#  medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : ajisetiawan716
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username
  whatsapp          : 6283861160442
  telegram          : ajisetiawan716 


### Posts ###
permalink: /blog/:categories/:year/:month/:day/:title:output_ext
paginate: 6
paginate_path: /blog/page:num/

### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
 ### ADD SERVICE ###   
  service:
    output: true
    permalink: /services/:name
  ### END OF SERVICE ###  
  elements:                                             # For Documentation Only
    output: false                                        # For Documentation Only


### Disqus ###
disqus:
  shortname: ajisetiawan                      # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id

### Google Translate ###
tagmanager:
  enabled: true                                        # Set true to enable google Adsense
  google:
    tag_id: GTM-5BQ3JVM

### Google Translate ###
translate:
  enabled: true                                        # Set true to enable google translate

### AdBlock Detection ###
adblock_detect:
  enabled: true                                        # Set true to enable adblock detection

### Buy me a coffee ###
# See https://www.buymeacoffee.com/
buymeacoffee:
  enabled: false
  username: your_username
  color: "#007bff"
  message: "Thank you for visiting."                    # Message to be displayed aside from the button for a few seconds.
  description: "Support me on Buy me a coffee!"


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"                                   # For Documentation Only
  ### SERVICE ADD ###
  - scope:
      path: ""
      type: "service"
    values:
      layout: "page"
  ### END OF SERVICE ADD ###    
  - scope:
      path: ""
      type: "posts"
    values:
      comments: true                                   # Set to true to enable disqus comments


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
