### Site Settings ###
title               : Aji Setiawan
description         : >-
                      Mahasiswa Program Studi Manajemen Bisnis Syariah, Desainer Grafis, Webgrammer amatiran. 
                      Lihat proyek, portofolio, tulisan dan profilku di menu pojok kanan atas.
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : ajisetiawan716/ajisetiawan716.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : ajisetiawan716/portfolYOU
open_new_tab        : false                             # Opens external URLs in new tab (works for posts, projects and navbar only)
breadcrumbs         : true # true, false (default)

## Contact Form Settings ##
contact_form: https://formspree.io/f/mrgngpbk # Using Formspree.io backend
gsite_recapthca: 6Ld690EpAAAAACGGrqDlNyzFKmjE7rTgQkhGT2QT

### Plugins ###
plugins: 
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji
  - jekyll-tagging-related_posts


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md/**                           # For Documentation Only
  - pay/index.html/**
  - ig.html
  - wa.html
  - tg.html

### Author Info ###
author:
  name              : Aji Setiawan 
  image             : https://avatars.githubusercontent.com/u/106381048?v=4
# behance           : your_username
# dribbble          : your_username
  email             : email@ajisetiawan.my.id
  facebook          : adjiee.setiawan
  github            : ajisetiawan716
# gitlab            : your_username
  instagram         : ajisetiawan716
# kaggle            : your_username
  linkedin          : ajisetiawan716
#  medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : ajisetiawan716
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username
  whatsapp          : 6283861160442
  telegram          : ajisetiawan716
  paypal            : ajisetiawan716


### Posts ###
permalink: /blog/:year/:month/:day/:title:output_ext
paginate: 4
paginate_path: "/blog/page-:num/"

### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
 ### ADD SERVICE ###   
  service:
    output: true
    permalink: /services/:name
  ### END OF SERVICE ###  
  elements:                                             # For Documentation Only
    output: false                                        # For Documentation Only


### Disqus ## #comments:
comments:
  provider               : "disqus" # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "custom"
  disqus:
    shortname            : "ajisetiawan" # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
      
# SEO Related
google_site_verification : "YOUR_GOOGLE_SITE_CODE"
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :
keywords                 : portfolio, resume, aji setiawan, ajisetiawan716, ajisetiawan, python, HTML, CSS, design graphic, desain grafis, personal website, indonesia, indonesian, indonesia freelancers, freelancer

### Analytics ###
analytics:
  provider: "google" # false (default), "google", "google-universal", "custom"
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id

### Google Adsense ###
tagmanager:
  enabled: true                                        # Set true to enable google Adsense
  google:
    tag_id: GTM-5BQ3JVM

### Google Translate ###
translate:
  enabled: true                                        # Set true to enable google translate

### AdBlock Detection ###
adblock_detect:
  enabled: true                                        # Set true to enable adblock detection

### Buy me a coffee ###
# See https://www.buymeacoffee.com/
buymeacoffee:
  enabled: false
  username: your_username
  color: "#007bff"
  message: "Thank you for visiting."                    # Message to be displayed aside from the button for a few seconds.
  description: "Support me on Buy me a coffee!"


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"                                   # For Documentation Only
  ### SERVICE ADD ###
  - scope:
      path: ""
      type: "service"
    values:
      layout: "page"
  ### END OF SERVICE ADD ###    
  - scope:
      path: ""
      type: "posts"
    values:
      comments: true # or false (default)
    # Posts defaults image
  - scope:
      path: "" # an empty string here means all files in the project
      type: posts # Apply the default values below only to posts
    values:
      image: cover-default-image.png
      image-alt: Default Image Post

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
