name: Monitor GitHub Pages Uptime

on:
  schedule:
    - cron: '*/5 * * * *'  # Check every 5 minutes

jobs:
  uptime:
    runs-on: ubuntu-latest
    steps:
      - name: Check GitHub Pages
        id: check
        run: |
          status=$(curl -o /dev/null -s -w "%{http_code}\n" https://ajisetiawan716.github.io/ajisetiawan716.github.io)
          echo "status=$status" >> $GITHUB_ENV

      - name: Send Status to Better Stack
        if: ${{ env.status != '200' }}
        run: |
          curl -X POST https://uptime.betterstack.com/api/v2/monitors \
          -H "Authorization: Bearer ${{ secrets.BETTERSTACK_UPTIME_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{
            "status": "down",
            "message": "GitHub Pages is down",
            "service": "GitHub Pages"
          }'
